### ISSUE TITLE
Using it in Stockholm, 0xp

### ISSUE THREAD

**Issue by Kariyou77** [finndev/PokeBuddy#101]
I used it with the longitude and latitude that was initally in the program. But I realized that I want to make it harder for Niantic to understand I'm using it so I changed the long+lat to my current IRL position.

But I don't get any xp anymore. Tried to download PokeBuddy again but still receiving 0xp (now even with the initial long+lat settings)

Anyone who can help?

**Comment by GeneralMaster** [comment]
It's not pokebuddy's fault.
You've been soft banned. Because you were jumping from one geo location to another at inhuman speed.
Depending on the speed/distance you'll be banned for a couple of minutes or hours.
I wouldn't do that too often. Just let some time pass until you log in at a different location so you could have theoretically traveled there in real life.

**Comment by Vanethir** [comment]
#16 should answer your question.
