### ISSUE TITLE
Tips To Not Get Banned! :D

### ISSUE THREAD

**Issue by JoeyIsLit** [finndev/PokeBuddy#1032]
So personally I have seen a lot of people expressing how scared they are of being permabanned. I totally get that because it's a scary thought. I think giving a list of tips will ease the stress of everyone :) 
Just so you know I am creditable in giving advise on this. I have 3 accounts all above 24 and I run 3 bots almost everyday and I have yet to be banned. 

Here are some tips for you if you were looking on how to be as safe as possible. 
1. Take into account travel time. Let's say you put in coordinates for New York. Immediately look up flight times from where you're located to New York (or where ever you chose) you can use https://www.google.ca/flights/ for me it'll be roughly 6 hours. So before logging onto the account at home, I'll wait 6 hours.
2.  Settings are key. Your walk speed and altitude are important. I set them both to 10 and haven't had a single problem. Walk speed can be increased if you want to more xp faster so I wouldn't go above 14 for that.
3. Don't choose the teleport to walk function
4. Don't leave the bot running all the time for ridiculous long times. Think of it this way. You're trying to trick Niantic into thinking you're hunting these pokemon and running around. Do you really think they'll believe you went on a 12 hour pokemon hunt every day for 6 days?? No. Absolutely not. My point is vary the time you run the bot and personally I wouldn't go above 10 hours because that's an insane amount of time to be hunting pokemon. This option is the most versatile so do what you want with different times and the amount of times per week etc.

**Comment by MariaBitterlich** [comment]
You shall only bot in the area of your IP.

**Comment by AlexCtasy** [comment]
Well I dont know about bots, because i never used it., I just use fake gps.. But ill tell you my experience xoaoxa, I never used bots but yesterday I tried to use Pokebuddy, so I go bed and in my computer was running the bot, today i wake up and go to work, there i started again botting with pokebuddy and then i got banned, i used all features but just can take items from pokestops, 12hours left and Now i able to take items from pokestops, btw I'll set up my fake gps to save location cords that I always farm and play gyms and well Ill never put fake locations off, cause if i Do it i get my own location.. Btw I never tried to go to another country.. Just playing in same cords all the time.

**Comment by JoeyIsLit** [comment]
@MariaBitterlich Very good point. Personally I like the Pokemon I get from other countries so I will continue going to Pier 39 in the USA and Sydney :)

**Comment by AlexCtasy** [comment]
@JoeyIsLit LOL i was always afraid to go another country to get pokemon, and people was doing it so easy xoaoxa, ill stay in my cords from my proper country xD safe play

**Comment by flixwito** [comment]
1. There's actually a "cooldown" for changing country. Maybe 2-6 hours. I tried to "travel" from Canada to Australia and waiting for 5 hours, and i didn't get ban.
Of course, it's safer to count and follow your actual travel time.

2. Recommended speed is between 5 - 15 km. I got an error when travelling over 20km/h.
I leave the altitude blank, because i got an error when i set it, even on 10.

3. Seriously, that "teleport moving" option is useless.  -.-

4. I'm taking a break every 3 hour.

5. Everyone is thinking about walking speed, lvl, pokemon CP, etc.
While the technical problem like IP or proxy are ignored XD

**Comment by Brightblazer** [comment]
Your not right about the running time cause I could play pogo in the central square of Athens where there are 3 poke stops with lures near a cafe so I could play legit for 7+++ hours and I could charge my phone also the only parameter could differ is the I wasn't moving

**Comment by Tr0nik0** [comment]
Hi, I just create one new account to try PB. There was no problems and the account is at level 12 right now. I want to try PB with my main account, but I'm not sure if I will banned...
