### ISSUE TITLE
Safe yet?

### ISSUE THREAD

**Issue by crilleaz** [finndev/PokeBuddy#364]
Whats the risks?

**Comment by stavrosian** [comment]
i used it for an hour with no problems. 
I did jump locations to early though and now im soft banned :(

**Comment by crilleaz** [comment]
Yeah but how sure are we that they don't record everything and just ban?

**Comment by stavrosian** [comment]
I am not sure. This is why I am going to wait out the softban and only do botting in my local area for now.

**Comment by sWAGrOGER** [comment]
Unless finnDev made it so that you login via android it'll come up saying you've swapped to IOS from android if you're a IOS user you might not get caught but they isn't anything to say you won't get caught. So it's a little risky so keep it simple guys and you should be okay. If FinnDev has secured it he should probably do a write up explaining how it all works for us and how we have less chance of getting caught and Perm banned.

**Comment by TrapLordJesus** [comment]
its working good for me i have it run in my normal place that i go to on the week ends and i have had no problem so far

**Comment by barbaricacidman** [comment]
how do you knw if you have a soft ban?

**Comment by stavrosian** [comment]
pokemon would run away from me immediatly and i was getting 0 XP from pokestops.

**Comment by finndev** [comment]
@stavrosian You are softbanned

The bot is safe to use. You won't get banned, because now you randomly "use Android". Many people (including me) have two phones. DeviceID and so on is all taken care off (randomly on 1st launch).
