### ISSUE TITLE
How to gain more EXP per hour???

### ISSUE THREAD

**Issue by monkeysrule** [finndev/PokeBuddy#59]
when i first started i got about 40,000 for my first hour, which is perfect. each hour it goes down more and i dont understand why, im only getting about 18,000 per hour now and thats still nice but i want the 40,000 back. hes catching tons of pokemon and the area is filled with pokestops, anyone know why my exp went down so much and how i can get more?

**Comment by Vanethir** [comment]
A possible reason for the decreased amount of XP is the decreasing amount of new Pokemon caught. Once you catch a new Pokemon, you get an extra 500 XP. To get max XP/h turn every task on (Farm Pokestops/Pokemon + Evolving). You can try to play around with the walking speed/teleportation. Would expect teleportation to be fastest for leveling.

**Comment by monkeysrule** [comment]
thats very helpful! however i should of mentioned i was level 22 when i started this so i already had a ton of pokemon. i doubt he was catching anything new and i always had evolving turned off. im just wondering if my internet speed would effect the amount of exp gained. i read that you shouldnt go over 30km for walkijng speed or you risk a ban, so ive kept mine at 28 to be safe.

**Comment by Vanethir** [comment]
Though eggs won't hatch at speeds >15-20km/h, you shouldn't get any Soft Ban for values <100 since it's a realistic and even low speed for traveling with car. Had no problems with teleportation as well (in New York Central Park). Anyways 30 should be fine for >30k XP/h.

Also there are some other factors for decreased speed, which you can't influence anyways:

- Server Connection (from time to time there might be no Pokestops+Pokemon)
- Lure Modules (increased Speed if there are a lot of people using them)
- PokeBuddy Laggs/Bugs (i.e. Updating problem)

Server Connection is a huge problem I am having right now in New York. Probably lots of player trying to catch Pokemon there at the same time.
Your own connection should just have an effect if it's super slow or instable.
