### ISSUE TITLE
Google account login problem

### ISSUE THREAD

**Issue by zyf911** [finndev/PokeBuddy#69]
Does any one has a login problem with google account starting about 1 hour ago?

Thanks~

**Comment by Cr4fTeXe** [comment]
Yes i can confirm this issue. I just downloaded the bot and tried to log in with a google account. These are the logs:

`[P - 16:54:41] Attempting to Login...
[P - 16:54:41] Logging in with method: Google as Auth Provider
[P - 16:54:41] Doing Google login...
[P - 16:54:42] [Error] GoogleAuthError: BadAuthentication
[P - 16:54:42] [Error] GoogleAuthError: Please make sure you entered correct email/pass in settings
[P - 16:54:42] Failed to login.
[P - 16:54:42] Stopping...`

I checked the Login-Data multiple times and even tried it with a different Google account.
I think this is caused by a change of Google's api, because i had that problem with another bot too.

**Comment by Vanethir** [comment]
@Cr4fTeXe Did you check the Box for google login? You have to enter your full email as well. (Not just your google username)

**Comment by Cr4fTeXe** [comment]
@Vanethir Yes i did. And i found the solution to my problem already. I accidently mixed up the passwords for the accounts i was using.
Thank you for the help anyways :D

The bot is working very well now :+1:
