### ISSUE TITLE
Pokebuddy.Core.dll failed to download

### ISSUE THREAD

**Issue by MaartenBloemen** [finndev/PokeBuddy#722]
When I try to run pokebuddy using proxifier I get an error saying "Failed to download: Pokebuddy.Core.dll. Retry later". Any ideas on how to fix/bypass this?

**Comment by Thorben24** [comment]
This usually means that PokeBuddy isnt able to download files from github. What is the traffic control in Proxifier telling you? I think that your proxy got no connection (is offline).

**Comment by MaartenBloemen** [comment]
The proxy works fine when I use it for chrome, I can visit pages download stuff but pokebuddy doesn't seem to work with the proxy, i've tried every setting (socket 5, socket 4 and plain https) but none of the 3 options work

**Comment by Thorben24** [comment]
When you visit www.utrace.de - Is the displayed ip the ip adress of your proxy or your home ip? Are there maybe proxification rules in proxifier wrong?

Could you send me a screenshot of them and a screenshot of your proxifier traffic overview while you starting pokebuddy? This would help me to see where the problem is.

**Comment by MaartenBloemen** [comment]
I think i managed to fix it, i tried running pokebuddy through right click and then selecting the server i wanted to use insted of the proxification rules like you said. I now added it using proxification rules and now it seems to work. Thanks for the help @Thorben24 !
